### ISSUE TITLE
[Issue]

### ISSUE THREAD

**Issue by liampearson96** [nanite/BetterCompatibilityChecker#12]
### Mod version

BetterCompatibilityChecker-1.0.7-build.22+mc1.16.5.jar

### Forge mod loader version

forge-1.16.5-36.2.9

### Repeatable?

- [X] Yes

### Link to log files

https://paste.mozilla.org/7Jj6f6AS

### Steps to reproduce the issue

1.  Downloaded mod and put into mods folder
2.  Started server
3.  Stopped server and edited BCC config.
4.  Started server.

### Description of the issue you are having

For some reason it doesn't display any information other then 'incompatible Vanilla server'
Please let me know if i am doing something wrong?

![image](https://user-images.githubusercontent.com/11605270/163668250-d8097aaa-8123-4915-87c3-239f48fdb6f0.png)

![image](https://user-images.githubusercontent.com/11605270/163668260-1148c479-7782-49b8-a26c-bd919d3f27a3.png)

![image](https://user-images.githubusercontent.com/11605270/163668268-7b28404f-e753-4ada-aba9-3f188a0bb1bf.png)

### Information

- [X] I have provided as much information as possible

**Comment by Gaz492** [comment]
Looks like the link to the logs is invalid, would you be able to upload them again?

**Comment by liampearson96** [comment]
https://paste.mozilla.org/i441168M

@Gaz492 This one should be good

**Comment by Gaz492** [comment]
Thanks, the logs show that it loaded the config without any issues the only thing I can see is, I'm not sure if the server started fully, this would cause the server to show that it's a vanilla server.
Are you able to connect to the server at all?

**Comment by liampearson96** [comment]
> Thanks, the logs show that it loaded the config without any issues the only thing I can see is, I'm not sure if the server started fully, this would cause the server to show that it's a vanilla server. Are you able to connect to the server at all?

Yes the server is connectable. I can load into the server mine, place ect just fine.

**Comment by Gaz492** [comment]
> > Thanks, the logs show that it loaded the config without any issues the only thing I can see is, I'm not sure if the server started fully, this would cause the server to show that it's a vanilla server. Are you able to connect to the server at all?
> 
> Yes the server is connectable. I can load into the server mine, place ect just fine.

Ok, would you be able to upload the debug log?
It may contain more information as to whats going on.
