### ISSUE TITLE
[Feature Request] Port to 1.12.2

### ISSUE THREAD

**Issue by dani31c** [nanite/BetterCompatibilityChecker#13]
### Feature Description

1.12.2 is known for having sometimes large modpacks and different mods every time in mosts cases, having it on 1.12.2 would be useful for most modpacks

**Comment by xJon** [comment]
Would still be appreciated, and useful in every 1.12.2 modpack.

**Comment by Gaz492** [comment]
I currently dont have any plans to backport the mod to 1.12.2 mainly due to the lack of spare time.

**Comment by xJon** [comment]
That's unfortunate - if it can still be considered in the future, it'd be appreciated!
