### ISSUE TITLE
[Feature Request] Customizable message when server does not have BetterCompatibiltyChecker Mod

### ISSUE THREAD

**Issue by Kanzaji** [nanite/BetterCompatibilityChecker#17]
# Suggestion Description
From my testing, the mod is "disabled" when server part does not have the mod installed. It would be nice if the mod prompt would use the Forge Modlist checker to determine if the modlist is correct, but still show the warning the modpack could be on different version, with additional note (like latest version of the modpack that doesn't contain the mod, or customizable note from Dev)

# Why I would like this feature?
I think it would be really useful for packs that have been already released, but they did not add this mod from the first version 😅

**Comment by MichaelHillcox** [comment]
From what I know, the way this mod works is by having the server tell the client they are different. If the server can't do this by modifying the incoming packet, then the client has no way of actually knowing what version the server is on.

**Comment by Gaz492** [comment]
In addition to what Michael said, the mod data sent by forge to calculate the cross/tick has not been very accurate in older versions due to packet size limits, which is the reason I made this mod.

**Comment by Kanzaji** [comment]
I understand all the limitations, and I understand how the mod works 😅 But I was talking more of like a fallback when the mod is not present on the server, but it is on the Client. We all know the Forge mod data is not great, but it is something, and can be used as a fallback with custom message specified in the config, like "The server is at least on version 1.3.0 or lower" for the packs that added the mod later on. If that still doesn't make much sense let me know 😄

**Comment by Kanzaji** [comment]
Modpack dev however can do it in the config for client-side, and that is what I'm asking about 😄
The message would look something like this:

When server has BetterCompatibilityChecker:
![obraz](https://user-images.githubusercontent.com/60540476/224324215-243c2b64-2169-4ea2-9374-a58683805c70.png)

When server does not have BetterCompatibiltiChecker but modpack dev provided last version that doesn't have it installed.
(Or custom message, tbh I think custom one could be a bit better but it's your choice.)
![obraz](https://user-images.githubusercontent.com/60540476/224326595-0aeafddd-d427-4279-a5e3-380fe8503271.png)
(Perfect Photoshop skills I know 😆)

**Comment by Jake-E** [comment]
> Modpack dev however can do it in the config for client-side, and that is what I'm asking about 😄 The message would look something like this:
> 
> When server has BetterCompatibilityChecker: ![obraz](https://user-images.githubusercontent.com/60540476/224324215-243c2b64-2169-4ea2-9374-a58683805c70.png)
> 
> When server does not have BetterCompatibiltiChecker but modpack dev provided first version that has it installed. (Or custom message, tbh I think custom one could be a bit better but it's your choice.) ![obraz](https://user-images.githubusercontent.com/60540476/224326595-0aeafddd-d427-4279-a5e3-380fe8503271.png) (Perfect Photoshop skills I know 😆)

And how would the mod know that it's below 1.3.0? What if it's on 1.5.0?

**Comment by Jake-E** [comment]
Unfortunately, I don't think this is something that the team plans on adding. Thanks for the suggestion though :)
