### ISSUE TITLE
Request for use in a modpack.

### ISSUE THREAD

**Issue by TheRealGriind** [nanite/BetterCompatibilityChecker#18]
Hi, I saw this line: `All Rights Reserved unless stated otherwise. Distribution permission is given to FeedTheBeast and CurseForge for use in modpacks` on the curseforge page for the mod, however I just wanted to make sure I am still allowed to use it in my modpack.

I will be releasing the modpack on the Technic Launcher platform, not Curseforge (Hence why I wanted to make sure) and the modpack will be made more specifically for a certain server I am helping out.

Do I have your permission to use this mod in the modpack?

**Comment by TheRealGriind** [comment]
Edit: I switched over to the Curseforge platform. I am allowed to create a modpack with this mod installed there ,correct?

**Comment by Gaz492** [comment]
Yes, if your modpack is on curseforge you can use the mod
