### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by TheCoati** [nanite/BetterCompatibilityChecker#19]
Currently this mod is published as "All rights reserved".

Will this be changed in the future to allow usage in mod- packs?

At this moment all mod- packs that are being published through Modrinth will be rejected.

> These following mods are not allowed in Modrinth modpacks due to their license. Please contact the mod author directly for permission or remove the mod from your modpack:

`/overrides/mods/BetterCompatibilityChecker-1.1.21-build.48+mc1.18.2.jar`

**Comment by Gaz492** [comment]
I currently dont have plans on changing the license or uploading to modrinth at this time.

**Comment by Gaz492** [comment]
The main concern I have with them is their TOS
Number 10 point 3 at https://modrinth.com/legal/terms implies they can do whatever they want with my mod, There is also the lack of transparency on their side of who owns/controls modrith that raises concerns

**Comment by TheCoati** [comment]
That's a fair concern not to upload your mod to Modrinth. \
I have to state that mod- packs published through Modrinth do not require the mod to be uploaded at Modrinth. \
Modrinth packs are able to just download the mod from CurseForge if it's not published on their platform but due to the current license and no additional terms Modrinth will now reject any mod- packs that are published including this mod. 

In order to use this mod in other mod- packs I noticed it doesn't require a complete license change as long you state at CurseForge that attribution and backlinking is required it should be fine.

If still don't want to make these changes with the concerns about the Modrinth terms I respect this choice. \
Thanks for further explanation anyways.

**Comment by Gaz492** [comment]
If packs from modrinth is able to download from curseforge then im happy to state that and give you premission and have added a sentance at the bottom of the desciption stating that https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker

**Comment by Su5eD** [comment]
Hi, I understand your concerns regarding Modrinth's policy, though i believe it is a necessity to allow them to distribute the mod across their network. Modrinth is in fact very transparent and communicative with developers, so it's not done in bad faith.

On the other hand I must point out that CurseForge's terms also come with an almost equal clause, extended to last forever.  

[Overwolf Developers Terms and Conditions](https://overwolf.github.io/topics/legal/legal-developers-terms) Section 5, point ii.
> Developer hereby grants Overwolf and its agents a non-exclusive, royalty-free, fully paid-up license to display and distribute all Applications through the Platform during the term of this Agreement and, following the term of this Agreement, to retain “Mods” as further set forth in Section 13(iii). For clarity, nothing herein shall be interpreted to prohibit Developer's distribution of Mods in any manner. 

[Overwolf terms of use](https://www.overwolf.com/legal/terms/)
> By submitting or posting such Content, you grant Overwolf and its successors a worldwide, non-exclusive, royalty-free, perpetual, sub licensable and transferable license to use, copy, distribute, transmit, modify, prepare derivative works of, publicly display, and publicly perform such Content on, through or in connection with the Services in any media formats and through any media channels, including without limitation, for commercially promoting the Services. 

It seems a lot of developers have reservations about Modrinth's policies, though what they don't realize is that similar terms apply to CurseForge, too.

**Comment by Gaz492** [comment]
> Hi, I understand your concerns regarding Modrinth's policy, though i believe it is a necessity to allow them to distribute the mod across their network. Modrinth is in fact very transparent and communicative with developers, so it's not done in bad faith.
> 
> On the other hand I must point out that CurseForge's terms also come with an almost equal clause, extended to last forever.
> 
> [Overwolf Developers Terms and Conditions](https://overwolf.github.io/topics/legal/legal-developers-terms) Section 5, point ii.
> 
> > Developer hereby grants Overwolf and its agents a non-exclusive, royalty-free, fully paid-up license to display and distribute all Applications through the Platform during the term of this Agreement and, following the term of this Agreement, to retain “Mods” as further set forth in Section 13(iii). For clarity, nothing herein shall be interpreted to prohibit Developer's distribution of Mods in any manner.
> 
> [Overwolf terms of use](https://www.overwolf.com/legal/terms/)
> 
> > By submitting or posting such Content, you grant Overwolf and its successors a worldwide, non-exclusive, royalty-free, perpetual, sub licensable and transferable license to use, copy, distribute, transmit, modify, prepare derivative works of, publicly display, and publicly perform such Content on, through or in connection with the Services in any media formats and through any media channels, including without limitation, for commercially promoting the Services.
> 
> It seems a lot of developers have reservations about Modrinth's policies, though what they don't realize is that similar terms apply to CurseForge, too.

Im well aware the terms are very similar with curseforge, which makes them no better than curseforge, when people are portraying them as the better option, yes their site may work better in some aspects, but would you rather stick with the evil you know or the evil you dont know?
They could still be able to distribute our mods and modpacks without needing the derivative clause in the terms.

This is not to say I wont at some point add my mods to modrinth regardless of their terms, its just at this point im not planning on doing so.
