### ISSUE TITLE
Please make it for Fabric too

### ISSUE THREAD

**Issue by SharkieTV** [nanite/BetterCompatibilityChecker#2]
### Feature Description

Hi, I have added the mod into my Better MInecraft Modpack, hoping you will also make a Fabric Version lets them know if they are on the right version or not

**Comment by Gaz492** [comment]
I can have a go at making it for fabric as well, I don't think it should be too difficult.

**Comment by Gaz492** [comment]
I have released a beta version for fabric on CurseForge, There are some visual bugs but It looks to be working correctly.
One of the visual bugs have part of the tooltip render off screen if the screen size is too small (this is a vanilla bug) and the other makes the checkmark or x render behind the server you click on.

**Comment by SharkieTV** [comment]
Game crashing when clicking multiplayer
https://pastebin.com/bjZKTGUV

**Comment by Gaz492** [comment]
> Game crashing when clicking multiplayer https://pastebin.com/bjZKTGUV

Should be fixed now https://www.curseforge.com/minecraft/mc-mods/better-compatibility-checker/files/3557340

**Comment by SharkieTV** [comment]
yeah sorry been busy, works now, I did however for the forge version the latest it wasnt working and just showing the x because of the normal forge error reverting to previous wokred

**Comment by Gaz492** [comment]
This would normally only happen if the mod did not load, do you have a log for the server and client?
Also which version was this on 1.16 or 1.18

**Comment by SharkieTV** [comment]
1.18, I currently do not have a log for it

**Comment by Gaz492** [comment]
Ive just tested the lastest version of the mod on 1.18 and 1.18.1 and they seem to be working for me.
The best guess I have without a log is that the mod did not load on either the server or the client.
