### ISSUE TITLE
[Issue] Servers added do not ping while in server list.

### ISSUE THREAD

**Issue by Gbergz** [nanite/BetterCompatibilityChecker#20]
### Minecraft Version

1.20.1

### Modloader

47.0.19

### Mod version

BetterCompatibilityChecker-3.0.2-build.59+mc1.20.1

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

https://gist.githubusercontent.com/Gbergz/2dc57a6ba4f0841a68a52374b3ebf248/raw/6e949e949db027255f8a1e70d307d7875c544f20/gistfile1.txt

### Steps to reproduce the issue

1. Install mod.
2. Start a server with mod
3. add that server to multiplayer list.
4. try and ping it
5. doesnt work, stays at "pinging".
Profit.

### Description of the issue you are having

When the mod is active, no servers active are pinging or showing MoTD.

Also when staying for long enough in the Multiplayer menu you'll crash to desktop.
Crash-report for that here: https://gist.githubusercontent.com/Gbergz/065d8abb1df25b6c711f1604c153ae38/raw/1f9b8dd5ee33a33599a429b3a0e4d2877f60f0cf/gistfile1.txt

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
Can you confirm if the mod is installed on the client as well?

**Comment by Gbergz** [comment]
It is on both sides.

**Comment by Gaz492** [comment]
Thanks, a fixed version should be available on curseforge in around 20 minutes, depends how long it takes to get approved
