### ISSUE TITLE
Add the mod on Modrinth

### ISSUE THREAD

**Issue by AmibeSkyfy16** [nanite/BetterCompatibilityChecker#22]
### Feature Description

I think it would be great to see this mod on https://modrinth.com

Thank you for this cool project !

**Comment by MichaelHillcox** [comment]
The author of this mod has rules out using modrinth due to their over reaching ownership clause on their TOS

**Comment by Proxivirus** [comment]
Did Modrinth make a change to their TOS that led to this mod being uploaded? Or was it just decided that it was worth it due to the influx of users?
