### ISSUE TITLE
[Issue] Modrinth upload order for 1.20.1 versions is reversed

### ISSUE THREAD

**Issue by CorneliusCornbread** [nanite/BetterCompatibilityChecker#27]
### Minecraft Version

NA

### Modloader

NA

### Mod version

NA

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

NA

### Description of the issue you are having

Curseforge:
![image](https://github.com/nanite/BetterCompatibilityChecker/assets/8294697/dd6e234a-c49c-4f41-becb-79daca63cbe6)

Modrinth:
![image](https://github.com/nanite/BetterCompatibilityChecker/assets/8294697/896b29c6-4bd1-4a7c-bf86-b828d04f6aaf)

This issue sent me down a rabbit hole of discovering old bugs causing crashes. Resolved them by updating and simply using the CF download as opposed to the Modrinth download

### Information

- [X] I have provided as much information as possible

**Comment by Gaz492** [comment]
I don't believe that this is something I can change without possibly reuploading the files, which is something I am currently not planning on doing.

**Comment by CorneliusCornbread** [comment]
> I don't believe that this is something I can change without possibly reuploading the files, which is something I am currently not planning on doing.

Would you at least be willing to reupload the latest file? As currently it lists the oldest version as the latest version

**Comment by MichaelHillcox** [comment]
No, the platforms do not allow duplicate files.

**Comment by Fyoncle** [comment]
> I don't believe that this is something I can change without possibly reuploading the files, which is something I am currently not planning on doing.

You can atleast post a new version with 0 changes or whatever you want so it will be counted as the "latest" one.

**Comment by Gaz492** [comment]
Currently, I have no plans on releasing a new 1.20.1 build as I no longer have the dev env setup and our build scripts have changed, so an automated build won't work either.
I might get around to this eventually, but I have very little spare time and fixing this is very low on my list.
