### ISSUE TITLE
Question: What is useMetadata?

### ISSUE THREAD

**Issue by KaneHart** [nanite/BetterCompatibilityChecker#8]
### Mod version

bcc-fabric-1.0.4

### Repeatable?

- [ ] Yes

### Link to log files

None

### Description of the issue you are having

Just wondering what Meta was in this case. I noticed when people connect they hardly ever pay attention to the darn icon if it's outdated. Was hoping this might force tell them a message when they try to connect?

Thanks.

### Information

- [X] I have provided as much information as possible

**Comment by Gaz492** [comment]
useMetadata is for FTB modpacks, a metadata.json file is added to all FTB modpacks that contain the name and version of the modpack.

Adding a message when players try and connect with a different version is on my todo list though.
It would be along the lines of "It looks like you are not running the same version of the modpack as the server. Are you sure you want to connect?" type of thing
