### ISSUE TITLE
[Feature Request] Expose Mismatched Mod Channel List

### ISSUE THREAD

**Issue by ClaudiusMinimus** [nanite/BetterCompatibilityChecker#9]
### Feature Description

I use your mod in three of my packs and really like it. One feature nobody has done is to expose the mismatched mod channel list or specifically the mod(s) a server or client is missing. As a modpack developer, I would love to see this feature added as it would save me lots of time. Most client/server mods are very obvious, but there are times when someone pushes out a client mod that has no business on a server, but the server still requires it. It would be nice to have the list exposed so I could just add the missing mod and be done with it.
Thank you,
CM

**Comment by Gaz492** [comment]
This is something I would like to implement, but I'm not sure how feasible it is as there is only a certain amount of data that is able to be sent when the client queries the server, so if I added this feature, there is a chance it could not be accurate.

**Comment by Gaz492** [comment]
It looks like there is a PR on forge to do what you suggested, https://github.com/MinecraftForge/MinecraftForge/pull/8402 so I likely won't add this feature myself
